constants:
  quote_range: [2,4,6,8,10,12,14,16,18,20] # 报价区间
  switch_job_penalty: 0.01 # 跳槽惩罚
  labor_aversion_range: [0.2,0.45,0.7] # 劳动厌恶系数
  risk_aversion: 0.33 # 相对风险厌恶
  tax_rate_range: [0.05,0.1,0.15,0.2,0.25,0.3,0.35,0.4] #政府税率
  equality_param: 0.5 # 公平效率系数
  labor_range: [10,20,30,40,50,60,70,80,90,100] # 劳动者劳动量
  consumption_range: [20,40,60,80,100,120,140,160,180,200] # 劳动者消费量
  wage_range: [2,4,6,8,10,12,14,16,18,20] # 劳动者工资
  captial_elasticity: [0.25,0.45,0.7] # 资本弹性

  depreciation_rate: 0.01 # 折旧率
  investment_rate: 0.03 # 资产用于投资的比率
  swf_eq_param: 0.5 # 社会福利函数公平效率系数


# 一些训练相关的参数
train:
  gamma: 0.99 # 折扣因子
  lambda: 0.98 # GAE参数
  num_steps: 128 # 一轮rollout的步数
  n_minibatches: 4 # 训练时分的batch数
  worker_lr: 0.0005 # 劳动者学习率
  firm_lr: 0.0005 # 企业学习率
  government_lr: 0.0005
  entropy_coef_start: 0.5 # 熵正则化系数起始
  entropy_coef_end: 0.01 # 熵正则化系数退火结果
  ent_coef: 0.01 #若是固定系数，则设置为0.05
  ppo_update: 2 # 更新次数
  clip_param: 0.2 # PPO裁剪参数
  vf_coef: 0.5 # 价值函数系数
  max_grad_norm: 0.5 # 梯度裁剪
  total_timesteps: 100000 # 总训练步数
  seed: 20021117
  annealing_lr: True # 是否退火




size:
  action:
    worker: [10,10,10,4] # MultiDiscrete，消费量、报价、劳动量、工作企业(这里假定是4家，因为yaml不能引用变量)
    firm: [10,10] # 单位劳动工资、报价
    government: 8 # 税率
  observation:
    worker: 21 # 多一个公司增加1
    firm: 13 # 多一个公司增加2
    government: 22 # 多一个公司增加2

initialize:
  quote: 10.0 # 初始报价
  worker_asset: 3000.0 # 初始工人资产
  firm_asset: 15000.0 # 初始企业资产
  firm_capital: 1000 # 初始企业资本
  tax_rate: 0.10 # 初始税率
  wage: 10.0 # 初始工资

device: cuda
num_worker_agents: 10
num_firm_agents: 5
experiment:
  buffer_size: 10000